### ISSUE TITLE
USER STORY: Manage Site Content

### ISSUE THREAD

**Issue by mtmanning93** [mtmanning93/craft-front#1]
As a **site admin** I can **control all site content** so that **I can keep site content safe for all users**

## Acceptance Criteria

Create Data:
The site admin should be able to access a "Create Report" form. After inputting the needed information, submitting will store the new data in the database.

Read Data:
The site admin has the ability to read all content by viewing a list of objects and selecting one.

Update/ Delete Data:
The admin should have an option to edit and delete content and users. Each field related to the object should be editable with the ability to update the database information.

## Tasks

- [x] Install Django and other libraries/ dependencies (DRF)
- [x] Create Django superuser
- [x] Update the `admin.py` file to suit
- [x] Create necessary models and serialisers within each app
- [x] Test admin site has capabilities

**Comment by mtmanning93** [comment]
Capabilities in API view or admin site.
