### ISSUE TITLE
USER STORY: Delete Post

### ISSUE THREAD

**Issue by mtmanning93** [mtmanning93/craft-front#11]
As a **registered user** I can **delete a post** so that **I can remove it entirely from the site.**

## Acceptance Criteria

- Delete Button:
A user should see the option to delete their posts only on the posts they own throughout the site, using the same dropdown menu as #10 

- Confirmation:
Users must provide confirmation to delete a post

## Tasks

- [x] Add the delete option to the post settings dropdown menu
- [x] Implement a confirmation modal for post deletion
- [x] Redirect the user to the previous page if deletion is confirmed
- [x] Ensure post data is deleted from database

**Comment by mtmanning93** [comment]
Deletion of posts implemented in the backend.

**Comment by mtmanning93** [comment]
User story complete however in manual testing the deletion process a Bug was found, as a user can still navigate to the page via Url input see #31
