### ISSUE TITLE
USER STORY: Logout

### ISSUE THREAD

**Issue by mtmanning93** [mtmanning93/craft-front#12]
As a **registered, logged in user** I can **logout** so that **I can keep my account safe.**

## Acceptance Criteria

- Logout Link:
As the user is logged in the should be a link to logout available in the navbar

- Redirected:
When logout is selected the user should be redirected to the login form page

## Tasks

- [x] Implement a logout link in the logged in navbar
- [x] When a user logs out navbar links should change, relates to #2 
- [x] Redirect the logged out user to the home/ landing page

**Comment by mtmanning93** [comment]
Styling updated once logic is implemented
