### ISSUE TITLE
USER STORY: Top Posts 'WotW'

### ISSUE THREAD

**Issue by mtmanning93** [mtmanning93/craft-front#13]
As a **user** I can **view the 'top work of the week' (most liked)** so that **I can view and interact with it**

## Acceptance Criteria

- Work of the Week Component:
All users should be able to see a 'Work of the Week' component on all feed pages, showcasing the most liked work of the week.

- Posts:
Each post within the 'WotW' section should be clickable and redirects the user to the post details page.

## Tasks

- [x] Design and implement the UI for the WotW component
- [x] It should be highly visible on every feed page
- [x] Each post in the component should have the necessary information regarding the post visible in the preview
- [x] Clicking on one will direct the user to the post detail page of the that particular post instance
