### ISSUE TITLE
USER STORY: Employment Details

### ISSUE THREAD

**Issue by mtmanning93** [mtmanning93/craft-front#14]
As a **registered user** I can **share, and update my employment details** so that **other users can connect with the company.**

## Acceptance Criteria

- Employment Details Form:
Within the update profile section users should also be able to add and update current employment details and location to their profile. In order to showcase their work further. The form should include simple information to the company and must NOT be required so users can choose whether to provide the information or not.

- Visibility:
If provided, users employment details will be visible on their profile and on post details pages.

- Updating:
The information can be updated along with the profile information, deleting information form a field will delete the information from the relevant section of the site.

## Tasks

- [x] Create the UI form beneath the 'update profile' section, the form should include the following fields:
    - company name
    - trade/industry
    - location
- [x] Implement the correct data on the profile and post details pages.
- [x] Ensure the employment information is has a one to many relationship with the profile model

**Comment by mtmanning93** [comment]
Backend implementation of companies model complete. Users can add a maximum of 3 companies per profile. Other users can then select one of those companies as their 'employer'. Detail ERD screenshot if needed below.

![Image](https://github.com/mtmanning93/craft-front/assets/119814149/7c021a51-e7d6-4c53-bf9c-c681a9548937)
