### ISSUE TITLE
USER STORY: Profile Pages

### ISSUE THREAD

**Issue by mtmanning93** [mtmanning93/craft-front#15]
As a **registered user** I can **click a users avatar to visit their profile** so that **I can see their information and posts.**

## Acceptance Criteria

- Avatars:
The avatars site wide should be a clickable link to the relevant profile details page.

- Profiles:
Every user will have a profile page, the profile page will display all relevant information for that user. Including their profile card and beneath a list of all posts by the user instance.

## Tasks

- [x] Implement avatars as a link to the relevant user profile instance
- [x] Design the UI for the profile card, information should include:
    - avatar
    - name
    - joined date
    - number of posts
    - number of followers
    - number of following
    - if provided employment details
    - follow/ unfollow button #16 
- [x] Implement a post list below the profile card of only the profile instance posts
- [x] Implement the infinite scroll functionality
