### ISSUE TITLE
USER STORY: Follow/ Unfollow

### ISSUE THREAD

**Issue by mtmanning93** [mtmanning93/craft-front#16]
As a **registered user** I can **follow and unfollow other profiles** so that **I can see more or less of their content in my 'feed' page.**

## Acceptance Criteria

- Follow/ Unfollow Button:
A registered user should find a 'follow' button on all profiles which they do not follow, when clicked the button should change appearance and name to 'unfollow'.

- Follow Count:
When a user clicks follow, 3 things should happen:
    1) Their following count should increase by 1
    2) The profile instance they have clicked follow on should increase its follower count by 1
    3) The button should change

- Unfollow Count:
When a user clicks unfollow, two things should happen:
    1) Their following count should decrease by 1
    2) The profile instance they have clicked follow on should decrease its follower count by 1
    3) The button should change

## Tasks

- [x] Design and implement the Follow/ Unfollow button site wide on all profile instances.
- [x] Implement the logic to change the button from 'follow' to 'unfollow' and back
- [x] Implement the logic to update the count of both accounts involved in the 'follow'
- [x] Implement the logic to update both accounts involved in the 'unfollow'
- [x] Test working functionality thoroughly

**Comment by mtmanning93** [comment]
Logic is similar to that of a like and an approval, but for a profile, follow like and unlike funcitonality as a guide.
