### ISSUE TITLE
USER STORY: Top List

### ISSUE THREAD

**Issue by mtmanning93** [mtmanning93/craft-front#17]
As a **registered user** I can **view the list of 'Top Tradies'** so that **I can see who are the most approved accounts**

## Acceptance Criteria

- Top Page:
A top page can be navigated to where users can see a list of the most approved accounts.

- Profiles:
Each profile in the list displays necessary information and follow buttons, enabling other users to select from the list or follow the profile instance.

## Tasks

- [x] Design the UI for the 'Top' page
- [x] Design and implement each profile card with the relevant information and follow button
- [x] Implement the infinite scroll functionality to the list

**Comment by mtmanning93** [comment]
Working on styling
