### ISSUE TITLE
USER STORY: User Profile

### ISSUE THREAD

**Issue by mtmanning93** [mtmanning93/craft-front#18]
As a **registered user** I can **view my own profile and list of posts** so that **I can update and delete content and information.**

## Acceptance Criteria

- Profile Navigation:
A logged in user can easily navigate to their profile page from the navbar link.

- Edit/ Delete Options:
The owner of the profile and posts can see the options 'spanner' icon on all posts and profiles they own, once clicked they can choose the update or delete options.

## Tasks

- [x] Ensure logged in users have easy access to their personal profile page #2 
- [x] Implement the options icon menu on all posts they own, meaning all posts in the profile page and on their profile information card
- [x] Delete option should always trigger a 'delete confirmation' modal
