### ISSUE TITLE
USER STORY: Comment

### ISSUE THREAD

**Issue by mtmanning93** [mtmanning93/craft-front#19]
As a **registered user** I can **comment on a post** so that **I can join in the conversation and interact with other users.**

## Acceptance Criteria

- Comment Form:
Below each post details card and above the comments a registered user should have the availability to write comments and post them to the comments section #6.

- Delete Comment:
Comments which are owned by the current user should also have the option to be deleted.

- Ordering:
The latest comment should appear at the top of the comments.

## Tasks

- [x] Create the comment form, it should be simple with just a content text field and a post button
- [x] Implement the logic to post the comment to the top of the comments list
- [x] Ensure necessary information is visible on each comment instance:
    - avatar
    - name
    - date of comment
    - content
- [x] Implement a delete icon which triggers the 'delete confirmation' modal when clicked
- [x] Test the comment is deleted from the site and database

**Comment by mtmanning93** [comment]
Backend logic implemented

**Comment by mtmanning93** [comment]
Edit comment dropdown item included for further iterations
