### ISSUE TITLE
USER STORY: Navigation

### ISSUE THREAD

**Issue by mtmanning93** [mtmanning93/craft-front#2]
As a **user** I can **move through the site easily** so that **my experience when moving through the site is without frustration**

## Acceptance Criteria

- Logo:
The main Navbar should include a logo to identify the site easily and quickly. It should be clickable as the main home link.

- Nav Links:
The Navbar links should include links to signup and login for already registered users.

- Signup
The signup button should be bright and easily findable to attract new users.

## Tasks

- [x] Create the Navbar component
- [x] Include a large Logo as a link to the home page (left)
- [x] Link all links to necessary pages
- [x] Use Context and createContext() in app.js to get current user in order to alter the navigation links, the links to necessary help is below:
    - [Docs Link](https://legacy.reactjs.org/docs/context.html)
    - [Link to tutorial](https://learn.codeinstitute.net/courses/course-v1:CodeInstitute+RA101+2021_T3/courseware/70a8c55db0504bbdb5bcc3bfcf580080/b398c39fcbef44ca8b23dbac5e7f6067/)
- [x] Ensure to include a ternary statement with regards to logged in and registered user links.
    - When a new user the links should display 'sign up' and 'login' links
    - Registered users should see different links, see #3

**Comment by mtmanning93** [comment]
Install react router to enable page routing
