### ISSUE TITLE
USER STORY: Like/ Unlike

### ISSUE THREAD

**Issue by mtmanning93** [mtmanning93/craft-front#21]
As a **registered user** I can **like and unlike posts** so that **I can show my appreciation to posts I enjoy and have them appear in my liked feed**

## Acceptance Criteria

- Like Button:
Every post details instance should have a like icon below the image where users can click to like a post, the exact same icpn can then be clicked again to unlike the same post.

- Like Count:
The like count next to the icon should increase or decrease in relation to the action of the user

## Tasks

- [x] Implement a like icon and counter underneath the image on the post details page
- [x] Implement the logic needed to increase the count by 1 when liked, the icon must also change appearance (solid to border)
- [x] Create the logic to do the reverse when an image is already liked

**Comment by mtmanning93** [comment]
Like/ Unlike functionality enabled in the API
