### ISSUE TITLE
USER STORY: Update Profile

### ISSUE THREAD

**Issue by mtmanning93** [mtmanning93/craft-front#22]
As a **registered user** I can **update my personal profile information** so that **I can keep my personal information up to date.**

## Acceptance Criteria

- Update Profile Option:
When the user is on the profile page they own the options menu icon is visible. When clicked they can update their profile information and profile image, when clicking update the updated information is changed.

## Tasks

- [x] Implement the options menu on the profile page for the owner of the profile instance
- [x] Ensure data is updated when users have submitted their updates
- [x] Redirect user back to the profile page

**Comment by mtmanning93** [comment]
Complete, accept the employer field has a 'bug' as the employer must be a company instance, to fix this see feature request #38
