### ISSUE TITLE
USER STORY: Profile Approval

### ISSUE THREAD

**Issue by mtmanning93** [mtmanning93/craft-front#23]
As a **registered and logged in user** I can **approve a profile** so that **other user can see if they are a trusted worker or not. It will also allow them to make the 'top' list.**

## Acceptance Criteria

- Approval Button:
The user can identify and click an approve button found on every users profile.

- Update approval count:
Every profile has a visible approval count, showing other users how trusted their work is.

- Most approved:
User profiles with the most approvals will appear in the top page on the list of most approved.

## Tasks

- [x] Implement the backend logic to enable profiles to approve other profiles
- [x] Enable users to remove an approval
- [x] Disallow the approval of a users own profile in the backend
- [x] Design the button UI
- [x] Implement the logic to change the buttons appearance when clicked and the users approval count.

**Comment by mtmanning93** [comment]
Backend implementation complete

**Comment by mtmanning93** [comment]
Additionally added the logic to disallow own profile approval in the api
