### ISSUE TITLE
USER STORY: JWT User Access Authentication

### ISSUE THREAD

**Issue by mtmanning93** [mtmanning93/craft-front#24]
As a **registered user** I can ** securely access my account and private data using JWT authentication** so that **my account and related data is safe**

As a user of the web application, I want to be able to securely access my account and protected resources using JWT authentication.

## Acceptance Criteria

- Token:
When a user successfully logs in with valid credentials, they should receive a JWT token.

- Verification:
The server should verify the token on each request, ensuring validation, and that it is not expired.

- Access:
If the token is valid, the user should be granted access to the requested resource. Else they should receive an error response.

## Tasks

- [x] Install dependencies and update settings for JWT
- [x] Token verification is in place to ensure the security of user accounts and information
- [x] Error handling is implemented to address token related issues.
