### ISSUE TITLE
USER STORY: Deploy Backend

### ISSUE THREAD

**Issue by mtmanning93** [mtmanning93/craft-front#25]
As the **developer** I want **to deploy the backend to Heroku** so that **it is accessible and functional on the web**

## Acceptance Criteria

- API Functionailty:
The API appears and functions with correct functionality as seen in the local version. Running without any errors or issues.

- Accessibility:
The application is accessible via the Heroku URL.

## Tasks

- [x] Create ElephantSQL database
- [x] Create Heroku APP, add applicable `config-vars`
- [x] Enable automatic deploys and deploy
- [x] Check urls work as expected

**Comment by mtmanning93** [comment]
Manual testing all appears well, automated testing to be included.
