### ISSUE TITLE
USER STORY: Search Bar

### ISSUE THREAD

**Issue by mtmanning93** [mtmanning93/craft-front#28]
As a **user** I can **search each accessible feed** so that **i can filter the lists of posts**

## Acceptance Criteria

- Search Bar:
The search bar should be visible at the top of all feed pages, easily accessible.

- Searchable fields:
The search bar should search the fields related to the content on each page for example on the home or discover page, where all posts exist, it should search the publisher name, location, title.

The searchable fields for the top page should be name, number of approvals, employer, location

## Tasks

- [x] Design the UI for the search bar
- [x] Implement the search bar above the list of posts on each feed page.
- [x] Implement the logic behind the searchbar, searchable fields must be reviewed for each feed, see acceptance criteria above.
    - [x] Home/ Discover
    - [x] Feed
    - [x] Liked
    - [x] Top
