### ISSUE TITLE
USER STORY: Sign up

### ISSUE THREAD

**Issue by mtmanning93** [mtmanning93/craft-front#3]
As an **unregistered user** I can **sign up to an account** so that **I can enjoy the benefits of a registered user.**

## Acceptance Criteria

- Sign up Button:
When visiting the site it should be very clear where new users can sign up to a new account, an easily findable button for example.

- Sign Up Form:
When clicking the sign up link the user should be directed to a simple sign up form. When submitted the form the users profile should be created with their credentials.

- Sign up Information:
On signup a user should provide a username and password along with a password confirmation field.

## Tasks

- [x] Design and implement the UI for a bold 'signup' button visible in the Navbar.
- [x] Design and create a sign up form, ensuring to include 3 inputs:
    - username
    - password
    - password confirmation
- [x] Create a link to login form for misguided users who are already registered.
- [x] Direct users to the login page on signup
