### ISSUE TITLE
USER STORY: Post List

### ISSUE THREAD

**Issue by mtmanning93** [mtmanning93/craft-front#4]
As a **user** I can **view a list of all posts** so that **I have an overview of the entire site, and can easily select one to view more closely.**

## Acceptance Criteria

- Post List Page:
The user should be able to see a full list of all posts on the 'home/ discover' page (landing page)

- Infinite Scroll:
The page should only load posts as the user scrolls down and requires more content to avoid long load times.

- Post Info:
Each post in the list should display small necessary pieces of information enough for the user to decide if they wish to view the post details or not.

## Tasks

- [x] Create a posts app in the API, setting its ordering to `-created_at`
- [x] Design the UI for each post, key information should be provided:
    - avatar
    - owner
    - date created
    - title
    - image
    - likes count
    - comments count
- [x] In the front end render the list of posts to the home page
- [x] Implement infinite scroll functionality

**Comment by mtmanning93** [comment]
Backend list implemented
