### ISSUE TITLE
USER STORY: Post Details

### ISSUE THREAD

**Issue by mtmanning93** [mtmanning93/craft-front#5]
As a **user** I can **select a post and read its content** so that **I can read more information about it.**

## Acceptance Criteria

- Post Details:
When selecting a post the user should be directed to the post detail page where they can read its content in addition to a the other information seen on the post list page.

- Back Button:
The user should be able to easily return to the previous page, when finished.

- Interactive Sections:
A non registered user should be able to view the comments count, likes count and #6 

## Tasks

- [x] Create a post detail UI component for each post using JSX
- [x] Use the correct object fields to fill in the post template
- [x] Use a return icon to provide the user with a 'return to reports' option
- [x] Implement comment and like count icons under each image
- [x] Implement space for comments section underneath each post detail

**Comment by mtmanning93** [comment]
Comment section incomplete but included space in design.
