### ISSUE TITLE
USER STORY: View Comments

### ISSUE THREAD

**Issue by mtmanning93** [mtmanning93/craft-front#6]
As a **non-registered user** I can **view the comments left on each post** so that **I can read the conversation**

## Acceptance Criteria

- Comment Section:
A user should be able to scroll down below the post details to find the comment section.

- Comment:
Each comment should contain the commenter username, avatar, created date and of course content.

## Tasks

- [x] Create a comments section component 
- [x] Implement the comments section beneath the post details
- [x] Add the correct profile information to each individual comment
