### ISSUE TITLE
USER STORY: Login

### ISSUE THREAD

**Issue by mtmanning93** [mtmanning93/craft-front#8]
As a **registered user** I can **login to my account** so that **i can use the registered user functions of the site.**

## Acceptance Criteria

- Login link:
From the landing page a registered user should be able to easily find the link to login in the navbar.

- Login form:
Much like the signup form, registered user's should be directed to a login form, the username and password are required to login.

- Direction:
On login the user should be redirected to the home page

## Tasks

- [x] Implement a login option in the navbar #2 
- [x] Design and create the login form, users must give username and password credentials to login.
- [x] Implement the logic for error handling if the user is not registered already.
- [x] Provide a 'Dont have an account yet?' link beneath the login form for misguided users.
