### ISSUE TITLE
USER STORY: Create Posts

### ISSUE THREAD

**Issue by mtmanning93** [mtmanning93/craft-front#9]
As a **registered user** I can **create my own posts** so that **I can showcase my skills and work updates to the community**

## Acceptance Criteria

- Create Post Button:
As posts are the main feature of the site the create post button should be highly visible throughout the site, positioned in the navbar to registered and logged in users.

- Create Post Form Page:
The create post form page should be a simple form where a user can add necessary information and files to create a post in the database.

- Image selector:
Users should be able to select and image file within the form and reselect if they wanted a different image.

## Tasks

- [x] Design and implement an Add Post button, linking to the /posts/create/ endpoint
- [x] Design and implement the UI for the form with 3 inputs:
    - title
    - content
    - image file
- [x] Allow image file to be changed before post form submission
- [x] Implement correct form handling for incorrect inputs
- [x] Redirect post details when posted

**Comment by mtmanning93** [comment]
Tested that post is created via url and in the deployed API, success. Will ensure correct feed placement in posts list use story.
